#BUILD OF REACT
FROM node:12-alpine as build

#set working directory
WORKDIR /app

#install app dependencies
COPY package.json ./

#instal all node packeages
RUN npm install

#copy everything over to docker environment
COPY . .
RUN npm run build

########################################################################
#CREATE NGINX SERVER
#pull the official nginx:1.19.0 base image
FROM nginx:1.19.0
#copies React to the container directory
# Set working directory to nginx resources directory
WORKDIR /usr/share/nginx/html
# Remove default nginx static resources
RUN rm -rf ./*
# Copies static resources from builder stage
COPY --from=build /app/dist .
WORKDIR /app
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
# Containers run nginx with global directives and daemon off
CMD ["nginx", "-g", "daemon off;"]

##para heroku

##CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'