services:
  ##############################
  # Backend Container
  ##############################
  api-copywrite-container:
    restart: always
    image: copywrite-api  
    ports:
      - "3001:3001"

  ##############################
  # Frontend Container ##
  ##############################
  front-container:
    build:
        context: ./copywrite-frontend
        dockerfile: ./dockerfile
    image: copywrite-frontend:1.0
    ports:
      - "80:80"
      - "443:443"
    tty: true  