services:
  ##############################
  # Backend Container
  ##############################
  api-container:
    restart: always
    image: hagidev/copywrite-api:1.0  
    ports:
      - "3001:3001"

  ##############################
  # Frontend Container ##
  ##############################
  frontend-container:
    image: hagidev/copywrite-frontend:1.0
    ports:
      - "8080:80"
      - "443:443"
    tty: true  